### ISSUE TITLE
performance of local removal (enhancement question)

### ISSUE THREAD

**Issue by ak2k** [gauteh/lieer#113] opened 2019-07-19 13:03 UTC
I've noticed that after a large number of messages is deleted on the remote, it can take hours to propagate those deletions locally, as these are occurring for me at the rate of 1-2 messages per second:
removing messages:  20%|█████████▎                                    | 4283/21073 [46:18<7:36:46,  1.63s/it]

Might it be possible -- via batching or otherwise -- to improve the performance of this local message removal step?

**Comment by gauteh** [comment] 2019-07-19 21:04
Hm, do you have the chance to profile that? Removing files locally is done
after it is computed which files should be removed. There is an notmuch db
lookup, remove from db, delete file, and remove from gmailieer cache. But
hard to say which one of those is the problem. Perhaps the latter in case
you have a really huge amount of mail on the account.

I do not think the notmuch part can be batched, not the unlink on the disk
either as far as I know (I would be surprised if this is the problem), but
the cache update can probably be sped up by using sets and differences.

**Comment by ak2k** [comment] 2019-07-19 22:21
Sure, what would be the most useful way to capture a profile?

**Comment by gauteh** [comment] 2019-07-20 19:27
Try #114.

**Comment by ak2k** [comment] 2019-07-22 19:56
Thank you. I am capturing that now and can send it along when it finishes. For the current batch of 76k deletions (running 1-3 it/s), it is estimated to take a couple days, which I think is quite a bit longer than the initial/from-scratch sync. 

Hence, meanwhile, I tried capturing some stack trace samples with py-spy. If I interpret correctly the output (below), it appears that the majority of the time is being spent in the notmuch remove_message call. As you mentioned, it doesn't appear that the current notmuch python API (nor do the lower-level notmuch implementations) for message removal offer a multi-message interface, so batching doesn't seem viable.

Other than destroying my local state and starting fresh, are there any other approaches or even workarounds that come to mind? Perhaps the notmuch/xapian index could be rebuilt from a clean local message cache (to avoid unnecessarily re-downloading all the messages)?

FWIW, before capturing this trace, I experimented with wrapping the remove loop [gmailieer.py:494] in notmuch's begin_atomic/end_atomic and didn't notice much difference. 

Stack trace sample aggregation across several minutes during the extended 'removing messages' step (running 1-3 it/s):
```
$ sudo py-spy --native --pid 79442
Collecting samples from 'pid: 79442' (python v3.7.4)
Total Samples 45919, Error Rate 1.15% (Compact page out of bounds)
GIL: 0.00%, Active: 99.00%, Threads: 2

  %Own   %Total  OwnTime  TotalTime  Function (filename:line)
  0.00%  99.00%   0.000s    453.5s   runctx (cProfile.py:100)
  0.00%  99.00%   0.000s    453.5s   runctx (profile.py:62)
  0.00%  99.00%   0.000s    453.5s   <module> (gmi:8)
  0.00%  99.00%   0.000s    453.5s   _run_module_as_main (runpy.py:193)
  0.00%  99.00%   0.000s    453.5s   main (cProfile.py:178)
  0.00%  99.00%   0.000s    453.5s   runctx (cProfile.py:20)
  0.00%  99.00%   0.000s    453.5s   <module> (cProfile.py:185)
  0.00%  99.00%   0.000s    453.5s   _run_code (runpy.py:85)
  0.00%  99.00%   0.000s    453.5s   main (lieer/gmailieer.py:157)
  0.00%  99.00%   0.000s    453.5s   pull (lieer/gmailieer.py:353)
  0.00%  99.00%   0.010s    453.5s   partial_pull (lieer/gmailieer.py:495)
  0.00%  99.00%   0.000s    453.0s   remove_message (notmuch/database.py:554)
  0.00%  99.00%   0.000s    453.0s   remove (lieer/local.py:386)
  0.00%  99.00%   0.000s    452.4s   _ffi_call (_ctypes.cpython-37m-darwin.so)
  0.00%  99.00%   0.000s    452.4s   __ctypes_callproc (_ctypes.cpython-37m-darwin.so)
  0.00%  99.00%   0.000s    452.4s   _ffi_call_unix64 (_ctypes.cpython-37m-darwin.so)
  0.00%  99.00%   0.000s    452.4s   _PyCFuncPtr_call (_ctypes.cpython-37m-darwin.so)
  0.00%  99.00%   0.000s    452.4s   _notmuch_database_remove_message (libnotmuch.5.dylib)
  0.00%  99.00%   0.000s    450.7s   __notmuch_message_delete (libnotmuch.5.dylib)
  0.00%  99.00%   0.000s    450.2s   Xapian::Enquire::get_mset const (libxapian.30.dylib)
  0.00%  99.00%   0.000s    450.2s   Xapian::Enquire::Internal::get_mset const (libxapian.30.dylib)
  0.00%  99.00%   0.000s    450.2s   MultiMatch::get_mset (libxapian.30.dylib)
  0.00%  99.00%   0.000s    450.2s   LocalSubMatch::get_postlist (libxapian.30.dylib)
  0.00%  99.00%   0.000s    450.1s   Xapian::Database::has_positions const (libxapian.30.dylib)
  4.00%  99.00%   22.34s    449.0s   Inverter::has_positions const (libxapian.30.dylib)
 28.00%  72.00%   141.3s    330.0s   std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, st
  0.00%  78.00%   0.000s    225.2s   __notmuch_query_search_documents (libnotmuch.5.dylib)
  0.00%  21.00%   0.000s    225.0s   __notmuch_query_count_documents (libnotmuch.5.dylib)
  0.00%  44.00%    5.15s    179.8s   std::__1::__tree_iterator<std::__1::__value_type<unsigned int, std::__1::basic_string<char, std::__1::char_tra
  1.00%  28.00%    9.25s    123.5s   std::__1::unique_ptr<std::__1::__tree_node<std::__1::__value_type<unsigned int, std::__1::basic_string<char, s
  0.00%  23.00%    1.97s    85.57s   operator new (libc++abi.dylib)
  1.00%  21.00%    5.20s    85.41s   std::__1::__tree<std::__1::__value_type<unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>
  0.00%  22.00%    2.55s    84.05s   _malloc (libsystem_malloc.dylib)
  1.00%  21.00%    3.89s    80.46s   _malloc_zone_malloc (libsystem_malloc.dylib)
  1.00%  19.00%    3.85s    74.92s   _szone_malloc_should_clear (libsystem_malloc.dylib)
  9.00%  18.00%   45.94s    71.43s   _tiny_malloc_should_clear (libsystem_malloc.dylib)
 11.00%  18.00%   25.98s    65.84s   _free_tiny (libsystem_malloc.dylib)
  4.00%   4.00%   40.59s    43.09s   std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string (libc++.1.
  3.00%   7.00%   17.42s    39.50s   _tiny_free_no_lock (libsystem_malloc.dylib)
 12.00%  12.00%   36.74s    36.74s   std::__1::__tree_node_base<void*>*& std::__1::__tree<std::__1::__value_type<unsigned int, std::__1::basic_stri
  4.00%   9.00%   15.69s    25.17s   _tiny_malloc_from_free_list (libsystem_malloc.dylib)
  0.00%   4.00%    7.30s    18.53s   _free (libsystem_malloc.dylib)
  2.00%   2.00%   14.42s    14.42s   _tiny_free_list_add_ptr (libsystem_malloc.dylib)
  0.00%   3.00%    2.63s    12.90s   std::__1::__tree<std::__1::__value_type<unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>
  1.00%   4.00%    2.01s    11.39s   _szone_size (libsystem_malloc.dylib)
  3.00%   3.00%   11.36s    11.36s   _tiny_free_list_remove_ptr (libsystem_malloc.dylib)
  4.00%   4.00%   10.90s    10.90s   void std::__1::__tree_balance_after_insert<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void
  3.00%   3.00%    9.79s     9.79s   _tiny_size (libsystem_malloc.dylib)
  4.00%   4.00%    6.75s     6.75s   _set_tiny_meta_header_in_use (libsystem_malloc.dylib)
  3.00%   3.00%    2.35s     2.35s   _default_zone_malloc (libsystem_malloc.dylib)
  0.00%   0.00%    2.18s     2.18s   _default_zone_free_definite_size (libsystem_malloc.dylib)
  0.00%   0.00%    1.66s     1.66s   std::__1::unique_ptr<std::__1::__tree_node<std::__1::__value_type<unsigned int, std::__1::basic_string<char, s
  0.00%   0.00%   0.000s     1.55s   __notmuch_message_remove_filename (libnotmuch.5.dylib)
  0.00%   0.00%   0.000s     1.53s   Xapian::Document::Internal::remove_term (libxapian.30.dylib)
  0.00%   0.00%   0.000s     1.53s   __notmuch_message_remove_term (libnotmuch.5.dylib)
  0.00%   0.00%   0.000s     1.52s   Xapian::Document::Internal::need_terms const (libxapian.30.dylib)
  0.00%   0.00%   0.000s     1.45s   GlassTermList::positionlist_begin const (libxapian.30.dylib)
  0.00%   0.00%   0.000s     1.45s   Xapian::TermIterator::positionlist_begin const (libxapian.30.dylib)
  0.00%   0.00%   0.000s     1.44s   GlassWritableDatabase::open_position_list const (libxapian.30.dylib)
  0.00%   0.00%    1.17s     1.17s   _szone_free_definite_size (libsystem_malloc.dylib)
  0.00%   0.00%   0.010s    0.920s   GlassTable::find const (libxapian.30.dylib)
  0.00%   0.00%   0.000s    0.890s   GlassPositionList::read_data (libxapian.30.dylib)
  0.00%   0.00%   0.010s    0.890s   GlassTable::block_to_cursor const (libxapian.30.dylib)
  0.00%   0.00%   0.000s    0.870s   GlassTable::read_block const (libxapian.30.dylib)
  0.00%   0.00%   0.870s    0.870s   _pread (libsystem_kernel.dylib)
  0.00%   0.00%   0.000s    0.870s   io_read_block (libxapian.30.dylib)
  0.00%   0.00%   0.000s    0.860s   GlassCursor::find_exact (libxapian.30.dylib)
  0.00%   0.00%   0.300s    0.550s   Inverter::get_positionlist const (libxapian.30.dylib)
  0.00%   0.00%   0.000s    0.550s   GlassWritableDatabase::delete_document (libxapian.30.dylib)
  0.00%   0.00%   0.460s    0.470s   std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::operat
  0.00%   0.00%   0.450s    0.450s   operator delete (libc++abi.dylib)
  0.00%   0.00%   0.370s    0.370s   remove (lieer/local.py:389)
  0.00%   0.00%   0.000s    0.300s   Inverter::set_positionlist (libxapian.30.dylib)
  0.00%   0.00%   0.000s    0.300s   Inverter::delete_positionlist (libxapian.30.dylib)
  0.00%   0.00%   0.050s    0.250s   std::__1::__tree_const_iterator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char
  0.00%   0.00%   0.000s    0.170s   Inverter::remove_posting (libxapian.30.dylib)
  0.00%   0.00%   0.160s    0.170s   std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<unsigned int, std::__1::basic_string<char, std
  0.00%   0.00%   0.020s    0.160s   std::__1::__tree_iterator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std
  0.00%   0.00%   0.000s    0.130s   std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_tr
  0.00%   0.00%   0.000s    0.110s   std::__1::__tree_node_base<void*>*& std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::
  0.00%   0.00%   0.000s    0.080s   _bootstrap (threading.py:890)
  0.00%   0.00%   0.080s    0.080s   std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<unsigned int, unsigned int>, std::__1::__tree_
  0.00%   0.00%   0.000s    0.080s   _bootstrap_inner (threading.py:926)
  0.00%   0.00%   0.000s    0.080s   Inverter::PostingChanges::remove_posting (libxapian.30.dylib)
  0.00%   0.00%   0.070s    0.070s   ___unlink (libsystem_kernel.dylib)
  0.00%   0.00%   0.000s    0.070s   _unlink (libsystem_kernel.dylib)
  0.00%   0.00%   0.000s    0.070s   remove (lieer/local.py:387)
  0.00%   0.00%   0.010s    0.070s   GlassCursor::find_entry (libxapian.30.dylib)
  0.00%   0.00%   0.000s    0.070s   __pthread_start (libsystem_pthread.dylib)
  0.00%   0.00%   0.000s    0.060s   __notmuch_database_filename_to_direntry (libnotmuch.5.dylib)
  0.00%   0.00%   0.000s    0.060s   __notmuch_database_find_directory_id (libnotmuch.5.dylib)
  0.00%   0.00%   0.000s    0.060s   _notmuch_database_find_message_by_filename (libnotmuch.5.dylib)
  0.00%   0.00%   0.000s    0.060s   __notmuch_directory_create (libnotmuch.5.dylib)
  0.00%   0.00%   0.010s    0.050s   wait (threading.py:552)
  0.00%   0.00%   0.000s    0.050s   Xapian::PositionIterator::operator++ (libxapian.30.dylib)
  0.00%   0.00%   0.050s    0.050s   __platform_memmove$VARIANT$Haswell (libsystem_platform.dylib)
  0.00%   0.00%   0.000s    0.050s   run (tqdm/_monitor.py:69)
  0.00%   0.00%   0.000s    0.040s   std::__1::unique_ptr<GlassCursor, std::__1::default_delete<GlassCursor> >::reset (libxapian.30.dylib)
  0.00%   0.00%   0.000s    0.040s   GlassPostList::GlassPostList (libxapian.30.dylib)
```

A single (typical) stack trace sample:
```
$ sudo py-spy --native --pid 79442 --dump
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
Python version 3.7.4
Thread 0x700002C54000/2819 (idle)
	 ___psynch_cvwait (libsystem_kernel.dylib)
	 __pthread_cond_wait (libsystem_pthread.dylib)
	 wait (threading.py:300)
	 wait (threading.py:552)
	 run (tqdm/_monitor.py:69)
	 _bootstrap_inner (threading.py:926)
	 _bootstrap (threading.py:890)
	 __pthread_start (libsystem_pthread.dylib)
Thread 0x1163885C0/4611 (active)
	 std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::map<unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > >::pair (libxapian.30.dylib)
	 Inverter::has_positions const (libxapian.30.dylib)
	 Xapian::Database::has_positions const (libxapian.30.dylib)
	 LocalSubMatch::get_postlist (libxapian.30.dylib)
	 MultiMatch::get_mset (libxapian.30.dylib)
	 Xapian::Enquire::Internal::get_mset const (libxapian.30.dylib)
	 Xapian::Enquire::get_mset const (libxapian.30.dylib)
	 __notmuch_query_search_documents (libnotmuch.5.dylib)
	 __notmuch_message_delete (libnotmuch.5.dylib)
	 _notmuch_database_remove_message (libnotmuch.5.dylib)
	 _ffi_call_unix64 (_ctypes.cpython-37m-darwin.so)
	 _ffi_call (_ctypes.cpython-37m-darwin.so)
	 __ctypes_callproc (_ctypes.cpython-37m-darwin.so)
	 _PyCFuncPtr_call (_ctypes.cpython-37m-darwin.so)
	 remove_message (notmuch/database.py:554)
	 remove (lieer/local.py:386)
	 partial_pull (lieer/gmailieer.py:495)
	 pull (lieer/gmailieer.py:353)
	 main (lieer/gmailieer.py:157)
	 <module> (gmi:8)
	 runctx (cProfile.py:100)
	 runctx (profile.py:62)
	 runctx (cProfile.py:20)
	 main (cProfile.py:178)
	 <module> (cProfile.py:185)
	 _run_code (runpy.py:85)
	 _run_module_as_main (runpy.py:193)
```

**Comment by gauteh** [comment] 2019-07-22 20:55
Hm, interesting! I *think* you should be able to just comment out the `db.remove_message(..)` call at local.py:386 and just run `notmuch new` directly afterwards. Hopefully, the official CLI is faster! But, it could be a general performance issue in notmuch (i.e. I do not think that the latency is caused by the python bindings). Note that I am not 100% sure about the side-effects of commenting out those lines, from the notmuch side it is fine, but don't run `gmi sync` or a `gmi push` without doing `notmuch new`. Also probably worth doing a dry-run push/pull/sync afterwards (or backup first) just in case this causes all your email to be deleted.

**Comment by gauteh** [comment] 2019-08-28 10:53
Any further activity on this one? Otherwise closing.

**Closed** 2019-08-28 10:55 UTC
Labels: enhancement, notmuch
