### ISSUE TITLE
gmi sync didn't work

### ISSUE THREAD

**Issue by bkkavin** [gauteh/lieer#220] opened 2022-09-28 16:15 UTC
https://sqrtminusone.xyz/posts/2021-02-27-gmail/

I followed the instructions in above blog. I created an app password. 
When I ran gmi init mail@gmail.com browser opened and it showed all my google accounts. I selected the correct email. It asks for permissions. I pressed allow. It just shows " Something went wrong there. Try again". 
What should I do. Is there any other way to do this?

**Comment by gauteh** [comment] 2022-11-12 15:02
Still an issue?

**Comment by skangas** [comment] 2022-12-31 14:37
Duplicate of #215?

**Closed** 2022-12-31 14:39 UTC
