### ISSUE TITLE
Synchronising state across multiple devices

### ISSUE THREAD

**Issue by NickHu** [gauteh/lieer#112] opened 2019-07-16 09:33 UTC
Hi, I have a query about lieer's behaviour, and I'm not completely certain I am using it correctly.

I have lieer configured to use the same email account on both my desktop and my laptop, but it seems like it's almost impossible to keep them in sync without doing a force pull every time I open my laptop or power on my desktop.

I typically use gmail with the following workflow: once I read an email, I archive it; with notmuch, this corresponds to removing the 'inbox' tag from mail. So I will have a session on my desktop (say), where I archive a bunch of mail this way. Then I use `gmi sync` to push up my changes, and I can verify that in the gmail web UI those mails are archived as expected. However, my problems begin when I start using my laptop, which was synced with lieer before I archived that mail, so when I do a `gmi sync` there it goes and unarchives all that mail that I marked as archived on my desktop.

I've also tried doing a `gmi pull` on my laptop, as the first thing I do after turning it on, to rectify this, but it only completes a partial synchronisation (even if I repeatedly run `gmi pull`) - as soon as I do any notmuch operation, it's like that snapshot of the mailbox is marked as the most up-to-date (the timestamp probably gets updated or something), so my mail gets unarchived next time lieer syncs. The only solution I have found to this is to do a `gmi pull -f` immediately when I begin using a device, but this takes a really long time.

Can anyone else reproduce this kind of behaviour, and is there anything I can do to use lieer on multiple devices without having to force pull all the time?

**Comment by gauteh** [comment] 2019-07-16 11:06
Hm, normally `gmi pull` should overwrite local changes with the remote. These changes should have shown up in the history. Do you have any unsynced changes on the laptop? `gmi sync` first tries to do a `gmi push`, but it should fail if the local history is out of date - and thus requiring a `gmi pull` first.

**Comment by NickHu** [comment] 2019-07-16 15:58
That might be it - I'll try to be more dilligent about synchronising after every mailbox modification and then see if I still have the same issue.

**Comment by gauteh** [comment] 2019-08-28 10:55
Any activity on this one? closing for now.

**Closed by gauteh** 2019-08-28 10:55 UTC

**Comment by NickHu** [comment] 2019-08-29 08:47
Hi, I still get this. I think what happens is that when I'm browsing my mail on a second device (using alot and notmuch), even if the mailbox was last synced 2 days ago or something, if I in any way touch the mailbox by, for example, archiving an email, then the timestamp on the mailbox gets updated to the current time and then the sync gets out of whack when I try to use lieer. Maybe the right way to solve this is with http://www.muchsync.org/ or something?

**Comment by gauteh** [comment] 2019-08-29 09:19
What do you mean by mailbox? Muchsync should in theory work, but you probably have to also sync the lieer state files so that lieer knows which db revision has been symced with remote, and what remote revision has been synced with local.

**Comment by NickHu** [comment] 2019-08-29 14:56
By mailbox I mean Maildir. Often I will suspend my laptop for a few days at a time, during which time I might use my desktop and run lieer syncs and read my mail etc. Then when I open my laptop back up, if I use my mail client to archive or retag a mail before immediately doing a lieer sync, then all the changes from my desktop get trumped by this, because now chronologically the latest Maildir is the one on my laptop. Then when I run a lieer sync I get mail that I archived from my desktop being unarchived etc.

**Comment by gauteh** [comment] 2019-08-30 08:50
OK. And it works better if you do a `gmi pull` first (before modifying
anything on the laptop?). The only state in lieer is notmuch revision and
gmail historyId. The contents of the directory serve as a list of files
existing locally as well as the map between changed messages locally, and
the gmail message ID (contained in the file name).

**Comment by sachdevaprash** [comment] 2019-12-03 18:50
Any news on this? I have seen the same issue as well. I haven't yet characterized it very well.

My usage is mostly on gmail across multiple devices, with lieer only for one device.
When I pull on lieer first, it shows some missing message errors (I will add more detail when I'm on the device). And then when I push to gmail, I find that many of the messages are now archived. My guess is that this is not the expected behavior.

I tried reproducing this while using both devices at the same time, and had a tough time doing it, but it is definitely an issue I face. I will try to add more detailed reproduction method, but any advice would be useful.

**Comment by gauteh** [comment] 2019-12-03 19:24
Does lieer match the GMail interface?

**Comment by sachdevaprash** [comment] 2019-12-04 06:47
notmuch/lieer match the GMail interface after I do corrections after a sync.

After checking on the nature of the problem again, I find that there are 2 main problems.
1. inbox label is added to all main once synced. Thus unarchiving emails.
2. all new emails are marked as unread. And on syncing marked as unread for GMail too.

Is this some sort of a problem with my setup? From what I can tell, other gmail labels are respected.

**Comment by gauteh** [comment] 2019-12-04 07:22
You probably have unread and inbox as new tags, you might have missed a
step in the setup. Check the readme.

ons. 4. des. 2019, 07:47 skrev Prashant Sachdeva <notifications@github.com>:

**Comment by sachdevaprash** [comment] 2019-12-05 19:03
I'll check it out, and then reply here. Maybe that is the only problem. Thanks!

**Comment by sstepashka** [comment] 2023-07-20 17:33
@sachdevaprash did you check it? :)

**Comment by aspiers** [comment] 2024-09-29 17:31
@NickHu What was your conclusion on this?  I'm not 100% sure but I think I may be experiencing the exact same issues or at least very similar.

**Comment by aspiers** [comment] 2024-09-29 17:44
@gauteh I've had multiple incidents of email previously archived locally on one machine and synced via lieer reappearing on Gmail and the other machine, which I think is exactly what @NickHu originally reported here.  So I would suggest reopening this.  I can alternatively file a fresh issue.

Was lieer designed with the hub-and-spoke use case of two machines both synchronising to gmail at the same time?  I'm struggling to fully understand the syncing logic.  I think I do at least understand the server-side `historyId` mechanism, but it's not yet clear to me how lieer detects local changes which need pushing to the server, and exactly how it handles conflicts.  E.g. if a mail is archived on the server and locally the `unread` label is removed, what happens?

**Comment by aspiers** [comment] 2024-09-29 22:04
Actually don't reopen, it's likely this problem was due to [my stupidity](https://github.com/gauteh/lieer/issues/289#issuecomment-2381624204).  Sorry for the noise!

That said, I would still love to know the answers to the previous questions, but they deserve a separate issue.

**Comment by aspiers** [comment] 2024-09-30 08:52
> Actually don't reopen, it's likely this problem was due to [my stupidity](https://github.com/gauteh/lieer/issues/289#issuecomment-2381624204). Sorry for the noise!

_Actually_, no - I saw this again:

- fixed `new.tags` to be `' '` on both machines
- archived a bunch of email on my laptop
- ran `gmi sync` on my laptop
- verified that it correctly archived the email on Gmail
- (later) ran `gmi sync` on my desktop
- saw the following where in the `push` phase, it's unarchiving email

```
receiving metadata: 100%|████████████████████████████████████████████████████████████████████████resolving changes:   0%|                                                                                                                          | 0/29 [00:00<?, ?it/s]gid: 1923ee248c008708: add: ['INBOX'], remove: []
gid: 1923ee13e565e84e: add: ['INBOX'], remove: []
gid: 1923f11438b93fb7: add: ['INBOX'], remove: []
gid: 1923ee65849bdce8: add: ['INBOX'], remove: []
gid: 1923eedb9c65d602: add: ['INBOX'], remove: []
```

etc.

This is almost the exact [scenario @NickHu mentioned](https://github.com/gauteh/lieer/issues/112#issuecomment-526224081), albeit with desktop and laptop reversed.  So this issue should be reopened.

The first question is whether this scenario with two or more machines syncing with gmail in a hub-and-spokes topology is expected to work correctly?

> That said, I would still love to know the answers to the previous questions, but they deserve a separate issue.

Filed as #290.  I will also add more follow-up comments and questions there.

**Comment by aspiers** [comment] 2024-09-30 09:58
Argh. I thought of another possible explanation for this - it _could_ be the remnants of incorrect tagging from _before_ I [fixed the `new.tags` setting](https://github.com/gauteh/lieer/issues/289#issuecomment-2381624204).

To avoid creating further noise and possible false positives, I'll refrain from posting here further until I'm _super_ confident whether there's still an issue or not.  Sorry again!
